<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="todolistdiag"
    nsURI="http://todolistdiag/1.0" nsPrefix="todolistdiag">
  <eClassifiers xsi:type="ecore:EClass" name="Task">
    <eOperations name="getName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="setName" lowerBound="1">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getImportanceLevel" lowerBound="1" eType="#//Importance"/>
    <eOperations name="setImportanceLevel" lowerBound="1">
      <eParameters name="iLevel" eType="#//Importance"/>
    </eOperations>
    <eOperations name="getStatus" lowerBound="1" eType="#//Status"/>
    <eOperations name="getDescription" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="setDescription">
      <eParameters name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="statusNotStarted" lowerBound="1"/>
    <eOperations name="statusInProgress" lowerBound="1"/>
    <eOperations name="statusDone" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="#//Status"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importanceLevel" lowerBound="1"
        eType="#//Importance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongsTo" lowerBound="1"
        upperBound="-1" eType="#//Folder" eOpposite="#//Folder/contains"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        changeable="false" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Status">
    <eLiterals name="NOT_STARTED"/>
    <eLiterals name="IN_PROGRESS" value="1"/>
    <eLiterals name="DONE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Importance">
    <eLiterals name="LOW"/>
    <eLiterals name="MEDIUM" value="1"/>
    <eLiterals name="HIGH" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Folder">
    <eOperations name="setName">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getPrueba" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//Task" eOpposite="#//Task/belongsTo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//Folder"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="namespace" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prueba" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TasksManager">
    <eOperations name="createTask" lowerBound="1" eType="#//Task"/>
    <eOperations name="editTask">
      <eParameters name="task" eType="#//Task"/>
    </eOperations>
    <eOperations name="deleteTask">
      <eParameters name="task" eType="#//Task"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FoldersManager">
    <eOperations name="createFolder" lowerBound="1" eType="#//Folder"/>
    <eOperations name="editFolder">
      <eParameters name="folder" eType="#//Folder"/>
    </eOperations>
    <eOperations name="deleteFolder">
      <eParameters name="folder" eType="#//Folder"/>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
